version: '3'
services:
  nginx:
    image: nginx:1.20
    restart: always
    depends_on:
      - mysql
      - php
    links:
      - mysql
      - php
    volumes:
      - ./web:/var/www/html
      - ./nginx:/etc/nginx/conf.d/
      - ./certs:/certs 
    ports:
      - "80:80"
      - "443:443"
  php:
    image: php:fpm
    volumes:
      - ./web:/var/www/html
      - ./php:/usr/local/etc/php/php.ini
  mysql:
    image: mysql:8.0.28
    restart: always
    environment:
        - MYSQL_DATABASE=docker_demo
        - MYSQL_ROOT_PASSWORD=password_for_root
        - MYSQL_USER=kid
        - MYSQL_PASSWORD=kid_password
    ports:
        - "3306:3306"
    volumes:
        - mysql-db:/var/lib/mysql

volumes:
  mysql-db: